import type { Metadata } from 'next'
import { Jost } from 'next/font/google'

import './globals.css'
import Header from '@/components/Header/Header'
import Footer from '@/sections/Footer'

const jost = Jost({
  variable: '--font-jost',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${jost.className} text-black  bg-white antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
